hash-format = "sha256"

[[files]]
file = "LICENSE"

[[files]]
file = "config/DivineRPG.cfg"

[[files]]
file = "config/abyssalcraft.cfg"

[[files]]
file = "config/aether/AetherI.cfg"

[[files]]
file = "config/biomesoplenty/biomegen.cfg"

[[files]]
file = "config/biomesoplenty/biomeweights.cfg"

[[files]]
file = "config/biomesoplenty/ids.cfg"

[[files]]
file = "config/biomesoplenty/main.cfg"

[[files]]
file = "config/biomesoplenty/misc.cfg"

[[files]]
file = "config/biomesoplenty/structures/strongholds.cfg"

[[files]]
file = "config/biomesoplenty/structures/villages.cfg"

[[files]]
file = "config/biomesoplenty/terraingen.cfg"

[[files]]
file = "mods/abyssalcraft.pw.toml"
metafile = true

[[files]]
file = "mods/advent-of-ascension-nevermine.pw.toml"
metafile = true

[[files]]
file = "mods/adventure-backpack.pw.toml"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/animationapi.pw.toml"
metafile = true

[[files]]
file = "mods/aquaculture.pw.toml"
metafile = true

[[files]]
file = "mods/atomicstrykers-infernal-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/better-boat.pw.toml"
metafile = true

[[files]]
file = "mods/betterfps.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
metafile = true

[[files]]
file = "mods/buffed-tools.pw.toml"
metafile = true

[[files]]
file = "mods/campfire-backport.pw.toml"
metafile = true

[[files]]
file = "mods/chicken-chunk-patcher.pw.toml"
metafile = true

[[files]]
file = "mods/chunkpregenerator.pw.toml"
metafile = true

[[files]]
file = "mods/codechickencore.pw.toml"
metafile = true

[[files]]
file = "mods/damage-indicators-mod.toml"
metafile = true

[[files]]
file = "mods/dmod.pw.toml"
metafile = true

[[files]]
file = "mods/dummycore.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
metafile = true

[[files]]
file = "mods/electroblobs-wizardry.pw.toml"
metafile = true

[[files]]
file = "mods/enhanced-server-moderation.pw.toml"
metafile = true

[[files]]
file = "mods/et-futurum-requiem.pw.toml"
metafile = true

[[files]]
file = "mods/extraplanets.pw.toml"

[[files]]
file = "mods/farlanders.pw.toml"
metafile = true

[[files]]
file = "mods/fastcraft.pw.toml"
metafile = true

[[files]]
file = "mods/foamfix-optimization-mod.pw.toml"
metafile = true

[[files]]
file = "mods/fps-reducer.pw.toml"
metafile = true

[[files]]
file = "mods/galacticraft-planets.toml"

[[files]]
file = "mods/galacticraftcore.toml"

[[files]]
file = "mods/grimoire-of-gaia.pw.toml"
metafile = true

[[files]]
file = "mods/ichunutil.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-pets.pw.toml"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
metafile = true

[[files]]
file = "mods/iron-furnaces.pw.toml"
metafile = true

[[files]]
file = "mods/ivtoolkit.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
metafile = true

[[files]]
file = "mods/llibrary.pw.toml"
metafile = true

[[files]]
file = "mods/log4j2-jndi-exploit-fix.pw.toml"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
metafile = true

[[files]]
file = "mods/mb-battlegear-2.pw.toml"
metafile = true

[[files]]
file = "mods/micdoodle.toml"

[[files]]
file = "mods/minemenu.pw.toml"
metafile = true

[[files]]
file = "mods/mo-villages.toml"
metafile = true

[[files]]
file = "mods/more-planet-extras.pw.toml"

[[files]]
file = "mods/more-planets-gc-addon.pw.toml"

[[files]]
file = "mods/morph.pw.toml"
metafile = true

[[files]]
file = "mods/morpheus.pw.toml"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/mutant-creatures-mod.pw.toml"
metafile = true

[[files]]
file = "mods/natura.pw.toml"
metafile = true

[[files]]
file = "mods/nei-gtnh.toml"
metafile = true

[[files]]
file = "mods/official-divinerpg.toml"
metafile = true

[[files]]
file = "mods/openblocks.pw.toml"
metafile = true

[[files]]
file = "mods/openmodslib.pw.toml"
metafile = true

[[files]]
file = "mods/pandoras-box.pw.toml"
metafile = true

[[files]]
file = "mods/project-74246.pw.toml"
metafile = true

[[files]]
file = "mods/projecte.pw.toml"
metafile = true

[[files]]
file = "mods/random-things.pw.toml"
metafile = true

[[files]]
file = "mods/recurrent-complex-unofficial.pw.toml"
metafile = true

[[files]]
file = "mods/roguelike-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/server-tab-info.pw.toml"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
metafile = true

[[files]]
file = "mods/vampirism-become-a-vampire.pw.toml"
metafile = true

[[files]]
file = "mods/waila.pw.toml"
metafile = true
