name = "Pazzo Sgravato Anoinonpia"
author = "envy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "834d35e9defafeb0b9f1a7e8985d4454206fe49ee2b81cfb51145fb9853f1d38"

[versions]
forge = "10.13.0.1150"
minecraft = "1.7.10"
