name = "Pazzo Sgravato Anoinonpia"
author = "envy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9886151714732c697eda663fac8055e26dd6360e353a69830b015fe81f280ae"

[versions]
forge = "10.13.0.1150"
minecraft = "1.7.10"

[options]
no-internal-hashes = true
