name = "Pazzo Sgravato Anoinonpia"
author = "envy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13d68380d1cfbe62ade40ff524df8b32393d6d619bf9fb8096d5f3d0c3f5eadc"

[versions]
forge = "10.13.0.1150"
minecraft = "1.7.10"

[options]
no-internal-hashes = true
