name = "Pazzo Sgravato Anoinonpia"
author = "envy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9f35dfa11872ff2cbee2f5a69011d0012b2d7c6205d4e4ef3acd6440844ec39"

[versions]
forge = "10.13.0.1150"
minecraft = "1.7.10"

[options]
no-internal-hashes = true
