name = "Pazzo Sgravato Anoinonpia"
author = "envy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24fb37428dfd72aa72b10547e945e63cd560422675e4cda40cf033406f21b19a"

[versions]
forge = "10.13.0.1150"
minecraft = "1.7.10"
