name = "Pazzo Sgravato Anoinonpia"
author = "envy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a500590b295a32270a64c56760895bded1eb8839d0744d67110a607586da05"

[versions]
forge = "10.13.0.1150"
minecraft = "1.7.10"
